name: jd
on:
  schedule:
    - cron: 5 */3 * * *
  watch:
    types: started
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        ls
    - name: down
      run: |
        curl -O https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/jd_necklace_new.js
        curl -O https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/jd_joy_new.js
        curl -O https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/githubAction.md
        echo "========= 开始下载smiek2221的脚本 ========="
        git clone https://github.com/smiek2221/scripts.git  ./smiek2221
        rm -r ./smiek2221/USER_AGENTS.js
        cp -f ./smiek2221/*_*.js ./
        rm -rf ./smiek2221
        echo "========= 开始下载cdle的脚本 ========="
        git clone https://github.com/cdle/jd_study  ./cdle
        cp -f ./cdle/*_*.js ./
        rm -rf ./cdle
        echo "========= 开始下载Wenmoux的脚本 ========="
        git clone -b wen https://github.com/Wenmoux/scripts.git ./Wenmoux
        mv ./Wenmoux/jd/chinnkarahoi_jd_bookshop.js ./jd_bookshopWenmoux.js
        cp -f ./Wenmoux/jd/*_*.js ./
        rm -rf ./Wenmoux
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am '.更新'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: master
